import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import ThemeWrapper from "./components/ThemeWrapper";
import Navbar from "./components/Navbar";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const roboto = Roboto({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.className} antialiased`}
      >
        <ThemeWrapper>
          <main className="relative min-h-screen">
            <div className="">
              <Image
                src={"/bg.png"}
                alt="background"
                fill
                quality={100}
                className="object-cover -z-50 brightness-70"
              />
            </div>
            <Navbar />
            {children}
          </main>
        </ThemeWrapper>
      </body>
    </html>
  );
}
